### ISSUE TITLE
Transparency Issue with Biomes O' Plenty

### ISSUE THREAD

**Issue by rtx2090ti** [Someone-Else-Was-Taken/Magnesium#29] opened 2022-03-01 18:53 UTC
### Version information

magnesium 1.18 alpha.jar

### Expected Behavior

Biomes O' Plenty plants should be semi transparent, only the plant itself being visible

### Actual Behavior

With Magnesium installed, all of Biomes O' Plenty's vegetation turns solid black on pixels that are supposed to be transparent
![image](https://user-images.githubusercontent.com/100720436/156230692-f956c972-c64e-4fa7-ae9b-9eaed7de1d4b.png)

### Reproduction Steps

1. Install Magnesium
2. Install Biomes O' Plenty
3. Make a world and search for any Biomes O' Plenty biome with tall grass, clowers or any kind of vegetation that sticks out upwards from the grass

### Java version

Java 8 Update 311

### CPU

Ryzen 5 3600x

### GPU

RTX 2060 Super

### Additional information

Here's a complete list of my mods 
![image](https://user-images.githubusercontent.com/100720436/156230843-b8f77466-a7c6-40eb-a82d-03a86984f4be.png)

**Comment by SzczurekYT** [comment] 2022-03-05 07:31
Duplicate of #18

**Closed as completed** 2022-03-05 07:34 UTC
